CRITICAL - 2024-03-03 01:45:57 --> Error: Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 137.
 1 SYSTEMPATH\Database\Database.php(55): CodeIgniter\Database\Database->initDriver('pdo', 'Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(153): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\LoginController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\HP\\Desktop\\Proyecto Codineiter\\geotranck-dev\\public\\index.php')
CRITICAL - 2024-03-03 01:46:29 --> Error: Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 137.
 1 SYSTEMPATH\Database\Database.php(55): CodeIgniter\Database\Database->initDriver('pdo', 'Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(153): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\LoginController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\HP\\Desktop\\Proyecto Codineiter\\geotranck-dev\\public\\index.php')
CRITICAL - 2024-03-03 01:48:37 --> Error: Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 137.
 1 SYSTEMPATH\Database\Database.php(55): CodeIgniter\Database\Database->initDriver('pdo', 'Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(153): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\LoginController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 01:49:52 --> InvalidArgumentException: You have not selected a database type to connect to.
in SYSTEMPATH\Database\Database.php on line 52.
 1 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 2 SYSTEMPATH\Model.php(153): CodeIgniter\Database\Config::connect('default')
 3 APPPATH\Controllers\LoginController.php(11): CodeIgniter\Model->__construct()
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 01:58:44 --> ErrorException: Array to string conversion
in APPPATH\Controllers\LoginController.php on line 21.
 1 APPPATH\Controllers\LoginController.php(21): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'C:\\laragon\\www\\geotranck-dev\\app\\Controllers\\LoginController.php', 21)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 01:58:54 --> ErrorException: Array to string conversion
in APPPATH\Controllers\LoginController.php on line 21.
 1 APPPATH\Controllers\LoginController.php(21): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'C:\\laragon\\www\\geotranck-dev\\app\\Controllers\\LoginController.php', 21)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-03 02:53:56 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^ in C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM u...')
#2 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM u...')
#3 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM u...')
#4 C:\laragon\www\geotranck-dev\app\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#5 C:\laragon\www\geotranck-dev\app\Controllers\LoginController.php(12): App\Models\log_model->listarNombres()
#6 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\LoginController->index()
#7 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\geotranck-dev\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-03-03 02:53:56 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 2 APPPATH\Controllers\LoginController.php(12): App\Models\log_model->listarNombres()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:53:56 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 192.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 3 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 4 APPPATH\Controllers\LoginController.php(12): App\Models\log_model->listarNombres()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:53:56 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^', 'C:\\laragon\\www\\geotranck-dev\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM usuario')
 3 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 4 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 5 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 6 APPPATH\Controllers\LoginController.php(12): App\Models\log_model->listarNombres()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-03 02:54:32 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^ in C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM u...')
#2 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM u...')
#3 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM u...')
#4 C:\laragon\www\geotranck-dev\app\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#5 C:\laragon\www\geotranck-dev\app\Controllers\LoginController.php(12): App\Models\log_model->listarNombres()
#6 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\LoginController->index()
#7 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\geotranck-dev\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-03-03 02:54:32 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 2 APPPATH\Controllers\LoginController.php(12): App\Models\log_model->listarNombres()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:54:32 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 192.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 3 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 4 APPPATH\Controllers\LoginController.php(12): App\Models\log_model->listarNombres()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:54:32 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^', 'C:\\laragon\\www\\geotranck-dev\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM usuario')
 3 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 4 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 5 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 6 APPPATH\Controllers\LoginController.php(12): App\Models\log_model->listarNombres()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-03 02:55:11 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^ in C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM u...')
#2 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM u...')
#3 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM u...')
#4 C:\laragon\www\geotranck-dev\app\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#5 C:\laragon\www\geotranck-dev\app\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
#6 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\LoginController->index()
#7 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\geotranck-dev\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-03-03 02:55:11 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 2 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:55:11 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 192.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 3 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 4 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:55:11 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^', 'C:\\laragon\\www\\geotranck-dev\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM usuario')
 3 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 4 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 5 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 6 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-03 02:55:21 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^ in C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM u...')
#2 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM u...')
#3 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM u...')
#4 C:\laragon\www\geotranck-dev\app\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#5 C:\laragon\www\geotranck-dev\app\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
#6 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\LoginController->index()
#7 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\geotranck-dev\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-03-03 02:55:21 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 2 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:55:21 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 192.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 3 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 4 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:55:21 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^', 'C:\\laragon\\www\\geotranck-dev\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM usuario')
 3 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 4 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 5 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 6 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-03 02:55:25 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^ in C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM u...')
#2 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM u...')
#3 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM u...')
#4 C:\laragon\www\geotranck-dev\app\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#5 C:\laragon\www\geotranck-dev\app\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
#6 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\LoginController->index()
#7 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\geotranck-dev\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-03-03 02:55:25 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 2 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:55:25 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 192.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 3 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 4 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:55:25 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^', 'C:\\laragon\\www\\geotranck-dev\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM usuario')
 3 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 4 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 5 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 6 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-03 02:55:54 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^ in C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM u...')
#2 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM u...')
#3 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM u...')
#4 C:\laragon\www\geotranck-dev\app\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#5 C:\laragon\www\geotranck-dev\app\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
#6 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\LoginController->index()
#7 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\geotranck-dev\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-03-03 02:55:54 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 2 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:55:54 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 192.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 3 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 4 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:55:54 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^', 'C:\\laragon\\www\\geotranck-dev\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM usuario')
 3 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 4 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 5 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 6 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-03 02:55:55 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^ in C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM u...')
#2 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM u...')
#3 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM u...')
#4 C:\laragon\www\geotranck-dev\app\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#5 C:\laragon\www\geotranck-dev\app\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
#6 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\LoginController->index()
#7 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\geotranck-dev\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-03-03 02:55:55 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 2 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:55:55 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 192.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 3 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 4 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:55:55 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^', 'C:\\laragon\\www\\geotranck-dev\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM usuario')
 3 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 4 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 5 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 6 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-03 02:56:06 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^ in C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM u...')
#2 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM u...')
#3 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM u...')
#4 C:\laragon\www\geotranck-dev\app\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#5 C:\laragon\www\geotranck-dev\app\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
#6 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\LoginController->index()
#7 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\geotranck-dev\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-03-03 02:56:06 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 2 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:56:06 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 192.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 3 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 4 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:56:06 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^', 'C:\\laragon\\www\\geotranck-dev\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM usuario')
 3 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 4 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 5 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 6 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-03 02:56:08 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^ in C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM u...')
#2 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM u...')
#3 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM u...')
#4 C:\laragon\www\geotranck-dev\app\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#5 C:\laragon\www\geotranck-dev\app\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
#6 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\LoginController->index()
#7 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\geotranck-dev\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-03-03 02:56:08 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 2 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:56:08 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 192.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 3 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 4 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:56:08 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^', 'C:\\laragon\\www\\geotranck-dev\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM usuario')
 3 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 4 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 5 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 6 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-03 02:56:52 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^ in C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM u...')
#2 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM u...')
#3 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM u...')
#4 C:\laragon\www\geotranck-dev\app\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#5 C:\laragon\www\geotranck-dev\app\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
#6 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\LoginController->index()
#7 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\geotranck-dev\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-03-03 02:56:52 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 2 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:56:52 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 192.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 3 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 4 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:56:52 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^', 'C:\\laragon\\www\\geotranck-dev\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM usuario')
 3 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 4 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 5 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 6 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-03 02:57:24 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^ in C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM u...')
#2 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM u...')
#3 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM u...')
#4 C:\laragon\www\geotranck-dev\app\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#5 C:\laragon\www\geotranck-dev\app\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
#6 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\LoginController->index()
#7 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\geotranck-dev\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-03-03 02:57:24 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 2 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:57:24 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 192.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 3 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 4 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:57:24 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^', 'C:\\laragon\\www\\geotranck-dev\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM usuario')
 3 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 4 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 5 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 6 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-03 02:57:47 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^ in C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM u...')
#2 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM u...')
#3 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM u...')
#4 C:\laragon\www\geotranck-dev\app\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#5 C:\laragon\www\geotranck-dev\app\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
#6 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\LoginController->index()
#7 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\geotranck-dev\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-03-03 02:57:47 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 2 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:57:47 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 192.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 3 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 4 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:57:47 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^', 'C:\\laragon\\www\\geotranck-dev\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM usuario')
 3 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 4 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 5 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 6 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-03 02:57:48 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^ in C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM u...')
#2 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM u...')
#3 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM u...')
#4 C:\laragon\www\geotranck-dev\app\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#5 C:\laragon\www\geotranck-dev\app\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
#6 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\LoginController->index()
#7 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\geotranck-dev\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-03-03 02:57:48 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 2 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:57:48 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 192.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 3 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 4 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:57:48 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^', 'C:\\laragon\\www\\geotranck-dev\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM usuario')
 3 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 4 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 5 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 6 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-03 02:58:09 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^ in C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM u...')
#2 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM u...')
#3 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM u...')
#4 C:\laragon\www\geotranck-dev\app\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#5 C:\laragon\www\geotranck-dev\app\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
#6 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\LoginController->index()
#7 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\geotranck-dev\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-03-03 02:58:09 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 2 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:58:09 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 192.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 3 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 4 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:58:09 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^', 'C:\\laragon\\www\\geotranck-dev\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM usuario')
 3 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 4 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 5 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 6 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-03 02:58:09 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^ in C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM u...')
#2 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM u...')
#3 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM u...')
#4 C:\laragon\www\geotranck-dev\app\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#5 C:\laragon\www\geotranck-dev\app\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
#6 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\LoginController->index()
#7 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\geotranck-dev\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-03-03 02:58:09 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 2 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:58:09 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 192.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 3 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 4 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:58:09 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^', 'C:\\laragon\\www\\geotranck-dev\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM usuario')
 3 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 4 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 5 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 6 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-03 02:58:13 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^ in C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM u...')
#2 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM u...')
#3 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM u...')
#4 C:\laragon\www\geotranck-dev\app\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#5 C:\laragon\www\geotranck-dev\app\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
#6 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\LoginController->index()
#7 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\geotranck-dev\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-03-03 02:58:13 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 2 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:58:13 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 192.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 3 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 4 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:58:13 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^', 'C:\\laragon\\www\\geotranck-dev\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM usuario')
 3 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 4 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 5 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 6 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-03 02:59:44 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^ in C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM u...')
#2 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM u...')
#3 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM u...')
#4 C:\laragon\www\geotranck-dev\app\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#5 C:\laragon\www\geotranck-dev\app\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
#6 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\LoginController->index()
#7 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\geotranck-dev\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-03-03 02:59:44 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 2 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:59:44 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 192.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 3 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 4 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:59:44 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^', 'C:\\laragon\\www\\geotranck-dev\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM usuario')
 3 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 4 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 5 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 6 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-03 02:59:45 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^ in C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM u...')
#2 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM u...')
#3 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM u...')
#4 C:\laragon\www\geotranck-dev\app\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#5 C:\laragon\www\geotranck-dev\app\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
#6 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\LoginController->index()
#7 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\geotranck-dev\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-03-03 02:59:45 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 2 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:59:45 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 192.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 3 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 4 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:59:45 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^', 'C:\\laragon\\www\\geotranck-dev\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM usuario')
 3 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 4 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 5 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 6 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-03 02:59:46 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^ in C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM u...')
#2 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM u...')
#3 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM u...')
#4 C:\laragon\www\geotranck-dev\app\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#5 C:\laragon\www\geotranck-dev\app\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
#6 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\LoginController->index()
#7 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\geotranck-dev\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-03-03 02:59:46 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 2 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:59:46 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 192.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 3 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 4 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:59:46 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^', 'C:\\laragon\\www\\geotranck-dev\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM usuario')
 3 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 4 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 5 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 6 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-03 02:59:47 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^ in C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM u...')
#2 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM u...')
#3 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM u...')
#4 C:\laragon\www\geotranck-dev\app\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#5 C:\laragon\www\geotranck-dev\app\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
#6 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\LoginController->index()
#7 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\geotranck-dev\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-03-03 02:59:47 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 2 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:59:47 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 192.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 3 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 4 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:59:47 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^', 'C:\\laragon\\www\\geotranck-dev\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM usuario')
 3 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 4 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 5 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 6 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-03 02:59:48 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^ in C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM u...')
#2 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM u...')
#3 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM u...')
#4 C:\laragon\www\geotranck-dev\app\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#5 C:\laragon\www\geotranck-dev\app\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
#6 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\LoginController->index()
#7 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\geotranck-dev\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-03-03 02:59:48 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 2 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:59:48 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 192.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 3 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 4 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 02:59:48 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^', 'C:\\laragon\\www\\geotranck-dev\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM usuario')
 3 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 4 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 5 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 6 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-03 03:00:45 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^ in C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM u...')
#2 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM u...')
#3 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM u...')
#4 C:\laragon\www\geotranck-dev\app\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#5 C:\laragon\www\geotranck-dev\app\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
#6 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\LoginController->index()
#7 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\geotranck-dev\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-03-03 03:00:45 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 2 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 03:00:45 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 192.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 3 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 4 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 03:00:45 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^', 'C:\\laragon\\www\\geotranck-dev\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM usuario')
 3 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 4 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 5 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 6 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-03 03:04:12 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^ in C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM u...')
#2 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM u...')
#3 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM u...')
#4 C:\laragon\www\geotranck-dev\app\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#5 C:\laragon\www\geotranck-dev\app\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
#6 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\LoginController->index()
#7 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\geotranck-dev\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-03-03 03:04:12 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 2 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 03:04:12 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 192.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 3 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 4 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 03:04:12 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^', 'C:\\laragon\\www\\geotranck-dev\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM usuario')
 3 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 4 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 5 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 6 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-03 03:04:12 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^ in C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM u...')
#2 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM u...')
#3 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM u...')
#4 C:\laragon\www\geotranck-dev\app\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#5 C:\laragon\www\geotranck-dev\app\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
#6 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\LoginController->index()
#7 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\geotranck-dev\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-03-03 03:04:12 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 2 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 03:04:12 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 192.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 3 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 4 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 03:04:12 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^', 'C:\\laragon\\www\\geotranck-dev\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM usuario')
 3 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 4 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 5 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 6 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-03 03:04:13 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^ in C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM u...')
#2 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM u...')
#3 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM u...')
#4 C:\laragon\www\geotranck-dev\app\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#5 C:\laragon\www\geotranck-dev\app\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
#6 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\LoginController->index()
#7 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\geotranck-dev\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-03-03 03:04:13 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 2 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 03:04:13 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 192.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 3 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 4 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 03:04:13 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^', 'C:\\laragon\\www\\geotranck-dev\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM usuario')
 3 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 4 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 5 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 6 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-03 03:04:14 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^ in C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM u...')
#2 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM u...')
#3 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM u...')
#4 C:\laragon\www\geotranck-dev\app\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#5 C:\laragon\www\geotranck-dev\app\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
#6 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\LoginController->index()
#7 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\geotranck-dev\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-03-03 03:04:14 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 2 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 03:04:14 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 192.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 3 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 4 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 03:04:14 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^', 'C:\\laragon\\www\\geotranck-dev\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM usuario')
 3 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 4 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 5 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 6 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-03 03:04:15 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^ in C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM u...')
#2 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM u...')
#3 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM u...')
#4 C:\laragon\www\geotranck-dev\app\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#5 C:\laragon\www\geotranck-dev\app\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
#6 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\LoginController->index()
#7 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\geotranck-dev\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-03-03 03:04:15 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 2 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 03:04:15 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 192.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 3 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 4 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 03:04:15 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «usuario»
LINE 1: SELECT * FROM usuario
                      ^', 'C:\\laragon\\www\\geotranck-dev\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM usuario')
 3 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM usuario')
 4 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM usuario')
 5 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM usuario')
 6 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 03:10:40 --> ErrorException: Undefined variable $da4tos
in APPPATH\Controllers\LoginController.php on line 18.
 1 APPPATH\Controllers\LoginController.php(18): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $da4tos', 'C:\\laragon\\www\\geotranck-dev\\app\\Controllers\\LoginController.php', 18)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-03 03:10:55 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «acc44eso»
LINE 1: SELECT * FROM acc44eso
                      ^ in C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM a...')
#2 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM a...')
#3 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM a...')
#4 C:\laragon\www\geotranck-dev\app\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM a...')
#5 C:\laragon\www\geotranck-dev\app\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
#6 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\LoginController->index()
#7 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\laragon\www\geotranck-dev\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\geotranck-dev\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-03-03 03:10:55 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «acc44eso»
LINE 1: SELECT * FROM acc44eso
                      ^
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM acc44eso')
 2 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 03:10:55 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «acc44eso»
LINE 1: SELECT * FROM acc44eso
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 192.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM acc44eso')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM acc44eso')
 3 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM acc44eso')
 4 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 03:10:55 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «acc44eso»
LINE 1: SELECT * FROM acc44eso
                      ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «acc44eso»
LINE 1: SELECT * FROM acc44eso
                      ^', 'C:\\laragon\\www\\geotranck-dev\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT * FROM acc44eso')
 3 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('SELECT * FROM acc44eso')
 4 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM acc44eso')
 5 APPPATH\Models\log_model.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM acc44eso')
 6 APPPATH\Controllers\LoginController.php(13): App\Models\log_model->listarNombres()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 04:30:32 --> CodeIgniter\HTTP\Exceptions\HTTPException: Failed to parse JSON string. Error: Syntax error
in SYSTEMPATH\HTTP\IncomingRequest.php on line 588.
 1 SYSTEMPATH\HTTP\IncomingRequest.php(588): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidJSON('Syntax error')
 2 APPPATH\Controllers\LoginController.php(17): CodeIgniter\HTTP\IncomingRequest->getJSON()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->acceso()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 04:30:36 --> CodeIgniter\HTTP\Exceptions\HTTPException: Failed to parse JSON string. Error: Syntax error
in SYSTEMPATH\HTTP\IncomingRequest.php on line 588.
 1 SYSTEMPATH\HTTP\IncomingRequest.php(588): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidJSON('Syntax error')
 2 APPPATH\Controllers\LoginController.php(17): CodeIgniter\HTTP\IncomingRequest->getJSON()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->acceso()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 04:31:23 --> CodeIgniter\HTTP\Exceptions\HTTPException: Failed to parse JSON string. Error: Syntax error
in SYSTEMPATH\HTTP\IncomingRequest.php on line 588.
 1 SYSTEMPATH\HTTP\IncomingRequest.php(588): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidJSON('Syntax error')
 2 APPPATH\Controllers\LoginController.php(17): CodeIgniter\HTTP\IncomingRequest->getJSON()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->acceso()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 04:33:16 --> CodeIgniter\HTTP\Exceptions\HTTPException: Failed to parse JSON string. Error: Syntax error
in SYSTEMPATH\HTTP\IncomingRequest.php on line 588.
 1 SYSTEMPATH\HTTP\IncomingRequest.php(588): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidJSON('Syntax error')
 2 APPPATH\Controllers\LoginController.php(17): CodeIgniter\HTTP\IncomingRequest->getJSON()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->acceso()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 04:33:50 --> CodeIgniter\HTTP\Exceptions\HTTPException: Failed to parse JSON string. Error: Syntax error
in SYSTEMPATH\HTTP\IncomingRequest.php on line 588.
 1 SYSTEMPATH\HTTP\IncomingRequest.php(588): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidJSON('Syntax error')
 2 APPPATH\Controllers\LoginController.php(17): CodeIgniter\HTTP\IncomingRequest->getJSON()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->acceso()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 04:34:28 --> CodeIgniter\HTTP\Exceptions\HTTPException: Failed to parse JSON string. Error: Syntax error
in SYSTEMPATH\HTTP\IncomingRequest.php on line 588.
 1 SYSTEMPATH\HTTP\IncomingRequest.php(588): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidJSON('Syntax error')
 2 APPPATH\Controllers\LoginController.php(17): CodeIgniter\HTTP\IncomingRequest->getJSON()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->acceso()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 04:36:14 --> CodeIgniter\HTTP\Exceptions\HTTPException: Failed to parse JSON string. Error: Syntax error
in SYSTEMPATH\HTTP\IncomingRequest.php on line 588.
 1 SYSTEMPATH\HTTP\IncomingRequest.php(588): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidJSON('Syntax error')
 2 APPPATH\Controllers\LoginController.php(17): CodeIgniter\HTTP\IncomingRequest->getJSON()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->acceso()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 04:36:42 --> CodeIgniter\HTTP\Exceptions\HTTPException: Failed to parse JSON string. Error: Syntax error
in SYSTEMPATH\HTTP\IncomingRequest.php on line 588.
 1 SYSTEMPATH\HTTP\IncomingRequest.php(588): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidJSON('Syntax error')
 2 APPPATH\Controllers\LoginController.php(17): CodeIgniter\HTTP\IncomingRequest->getJSON()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->acceso()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 04:36:56 --> CodeIgniter\HTTP\Exceptions\HTTPException: Failed to parse JSON string. Error: Syntax error
in SYSTEMPATH\HTTP\IncomingRequest.php on line 588.
 1 SYSTEMPATH\HTTP\IncomingRequest.php(588): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidJSON('Syntax error')
 2 APPPATH\Controllers\LoginController.php(17): CodeIgniter\HTTP\IncomingRequest->getJSON()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->acceso()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 04:37:07 --> CodeIgniter\HTTP\Exceptions\HTTPException: Failed to parse JSON string. Error: Syntax error
in SYSTEMPATH\HTTP\IncomingRequest.php on line 588.
 1 SYSTEMPATH\HTTP\IncomingRequest.php(588): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidJSON('Syntax error')
 2 APPPATH\Controllers\LoginController.php(17): CodeIgniter\HTTP\IncomingRequest->getJSON()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->acceso()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 04:37:13 --> CodeIgniter\HTTP\Exceptions\HTTPException: Failed to parse JSON string. Error: Syntax error
in SYSTEMPATH\HTTP\IncomingRequest.php on line 588.
 1 SYSTEMPATH\HTTP\IncomingRequest.php(588): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidJSON('Syntax error')
 2 APPPATH\Controllers\LoginController.php(17): CodeIgniter\HTTP\IncomingRequest->getJSON()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->acceso()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 04:37:32 --> CodeIgniter\HTTP\Exceptions\HTTPException: Failed to parse JSON string. Error: Syntax error
in SYSTEMPATH\HTTP\IncomingRequest.php on line 588.
 1 SYSTEMPATH\HTTP\IncomingRequest.php(588): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidJSON('Syntax error')
 2 APPPATH\Controllers\LoginController.php(17): CodeIgniter\HTTP\IncomingRequest->getJSON()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->acceso()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 04:38:27 --> ErrorException: Attempt to read property "email" on null
in APPPATH\Controllers\LoginController.php on line 20.
 1 APPPATH\Controllers\LoginController.php(20): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "email" on null', 'C:\\laragon\\www\\geotranck-dev\\app\\Controllers\\LoginController.php', 20)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->acceso()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 04:38:35 --> ErrorException: Attempt to read property "email" on null
in APPPATH\Controllers\LoginController.php on line 20.
 1 APPPATH\Controllers\LoginController.php(20): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "email" on null', 'C:\\laragon\\www\\geotranck-dev\\app\\Controllers\\LoginController.php', 20)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->acceso()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 04:40:12 --> ErrorException: Attempt to read property "email" on null
in APPPATH\Controllers\LoginController.php on line 20.
 1 APPPATH\Controllers\LoginController.php(20): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "email" on null', 'C:\\laragon\\www\\geotranck-dev\\app\\Controllers\\LoginController.php', 20)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->acceso()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 04:40:20 --> ErrorException: Attempt to read property "email" on null
in APPPATH\Controllers\LoginController.php on line 20.
 1 APPPATH\Controllers\LoginController.php(20): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "email" on null', 'C:\\laragon\\www\\geotranck-dev\\app\\Controllers\\LoginController.php', 20)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->acceso()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-03 05:02:30 --> ErrorException: Attempt to read property "email" on null
in APPPATH\Controllers\LoginController.php on line 19.
 1 APPPATH\Controllers\LoginController.php(19): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "email" on null', 'C:\\laragon\\www\\geotranck-dev\\app\\Controllers\\LoginController.php', 19)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LoginController->acceso()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
